import type { Product } from "@/lib/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Paracetamol (Crocin, Dolo-650, Calpol)",
    price: 15.50,
    category: "Pain Relief",
    description: "Provides fast and effective relief from headaches, fever, and body aches.",
    uses: ["Pain relief", "Fever reduction"],
    sideEffects: ["Nausea", "Allergic reactions", "Liver damage (in case of overdose)"],
  },
  {
    id: "2",
    name: "Ibuprofen (Brufen, Combiflam)",
    price: 25.00,
    category: "Pain Relief",
    description: "Pain relief",
    uses: ["Pain relief", "Anti-inflammatory"],
    sideEffects: ["Stomach pain", "Heartburn", "Headache"],
  },
  {
    id: "3",
    name: "Eno",
    price: 80.00,
    category: "Acidity",
    description: "Acidity",
    uses: ["Acidity", "Heartburn", "Indigestion"],
    sideEffects: ["Bloating", "Stomach cramps"],
  },
    {
    id: "4",
    name: "Cofsils",
    price: 120.00,
    category: "Cold & Cough",
    description: "Cold & cough",
    uses: ["Sore throat", "Cough"],
    sideEffects: ["Numbness in mouth"],
  },
  {
    id: "5",
    name: "Cetirizine",
    price: 30.00,
    category: "Allergy",
    description: "Allergy",
    uses: ["Allergy", "Hay fever", "Hives"],
    sideEffects: ["Drowsiness", "Dry mouth", "Headache"],
  },
    {
    id: "6",
    name: "Glucon-D ORS",
    price: 20.00,
    category: "Dehydration",
    description: "Dehydration",
    uses: ["Dehydration", "Electrolyte imbalance"],
    sideEffects: ["Nausea", "Vomiting"],
  },
  {
    id: "7",
    name: "Multivitamins & Supplements (Becosules, Revital, Vitamin D, Zinc)",
    price: 300.00,
    category: "Vitamins & Supplements",
    description: "Multivitamins & Supplements",
    uses: ["Nutritional deficiencies"],
    sideEffects: ["Upset stomach", "Constipation", "Diarrhea"],
  },
  {
    id: "8",
    name: "Digital Thermometer",
    price: 250.00,
    category: "First Aid & Emergency",
    description: "Digital Thermometer",
    uses: ["Measuring body temperature"],
    sideEffects: [],
  },
    {
    id: "9",
    name: "Oximeter",
    price: 1500.00,
    category: "First Aid & Emergency",
    description: "Oximeter",
    uses: ["Measuring blood oxygen saturation"],
    sideEffects: [],
  },
  {
    id: "10",
    name: "Blood Pressure Monitor",
    price: 2000.00,
    category: "First Aid & Emergency",
    description: "Blood Pressure Monitor",
    uses: ["Measuring blood pressure"],
    sideEffects: [],
  },
  {
    id: "11",
    name: "Glucometer",
    price: 800.00,
    category: "First Aid & Emergency",
    description: "Glucometer",
    uses: ["Measuring blood glucose levels"],
    sideEffects: [],
  },
  {
    id: "12",
    name: "Bandages, cotton, antiseptic, scissors",
    price: 400.00,
    category: "First Aid & Emergency",
    description: "First Aid Kits",
    uses: ["Wound care"],
    sideEffects: [],
  },
  {
    id: "13",
    name: "Dettol Savlon, Betadine",
    price: 50.00,
    category: "First Aid & Emergency",
    description: "Antiseptics",
    uses: ["Disinfecting wounds"],
    sideEffects: ["Skin irritation"],
  },
  {
    id: "14",
    name: "Volini, Moov, Iodex",
    price: 150.00,
    category: "First Aid & Emergency",
    description: "Pain Relief Sprays/Gels",
    uses: ["Pain relief"],
    sideEffects: ["Skin irritation"],
  },
  {
    id: "15",
    name: "Hand Sanitizers (Dettol, Lifebuoy)",
    price: 60.00,
    category: "Personal Care & Hygiene",
    description: "Hand Sanitizers",
    uses: ["Disinfecting hands"],
    sideEffects: ["Dry skin"],
  },
  {
    id: "16",
    name: "Face Masks (N95, Surgical, Cloth)",
    price: 100.00,
    category: "Personal Care & Hygiene",
    description: "Face Masks",
    uses: ["Preventing the spread of germs"],
    sideEffects: [],
  },
  {
    id: "17",
    name: "Disposable Gloves",
    price: 120.00,
    category: "Personal Care & Hygiene",
    description: "Disposable Gloves",
    uses: ["Maintaining hygiene"],
    sideEffects: [],
  },
  {
    id: "18",
    name: "Wet Wipes",
    price: 40.00,
    category: "Personal Care & Hygiene",
    description: "Wet Wipes",
    uses: ["Cleaning skin"],
    sideEffects: ["Skin irritation"],
  },
  {
    id: "19",
    name: "Adult Diapers",
    price: 500.00,
    category: "Personal Care & Hygiene",
    description: "Adult Diapers",
    uses: ["Incontinence"],
    sideEffects: ["Skin irritation"],
  },
  {
    id: "20",
    name: "Whisper, Stayfree",
    price: 200.00,
    category: "Personal Care & Hygiene",
    description: "Women’s Hygiene Products",
    uses: ["Menstrual hygiene"],
    sideEffects: [],
  },
  {
    id: "21",
    name: "Sunscreen Lotus",
    price: 450.00,
    category: "Skin & Hair Care",
    description: "Sunscreens",
    uses: ["Sun protection"],
    sideEffects: ["Skin irritation"],
  },
  {
    id: "22",
    name: "Moisturizers Cetaphil",
    price: 250.00,
    category: "Skin & Hair Care",
    description: "Moisturizers",
    uses: [],
    sideEffects: [],
  },
  {
    id: "23",
    name: "Anti-acne creams Clindamycin gel",
    price: 350.00,
    category: "Skin & Hair Care",
    description: "Anti-acne creams",
    uses: [],
    sideEffects: [],
  },
  {
    id: "24",
    name: "Head & Shoulders shampoo",
    price: 280.00,
    category: "Skin & Hair Care",
    description: "Anti-dandruff Shampoos",
    uses: [],
    sideEffects: [],
  },
  {
    id: "25",
    name: "Pampers",
    price: 600.00,
    category: "Baby Care",
    description: "Baby Diapers",
    uses: [],
    sideEffects: [],
  },
  {
    id: "26",
    name: "Nestle Lactogen, Cerelac, Farex",
    price: 400.00,
    category: "Baby Care",
    description: "Baby Food",
    uses: [],
    sideEffects: [],
  },
  {
    id: "27",
    name: "Feeding Bottles",
    price: 700.00,
    category: "Baby Care",
    description: "Feeding Bottles & Sterilizers",
    uses: [],
    sideEffects: [],
  },
  {
    id: "28",
    name: "Mobility Aids Nebulizers",
    price: 2500.00,
    category: "Medical Devices & Mobility Aids",
    description: "Nebulizers",
    uses: [],
    sideEffects: [],
  },
  {
    id: "29",
    name: "Heating Pads",
    price: 800.00,
    category: "Medical Devices & Mobility Aids",
    description: "Heating Pads, Ice Packs",
    uses: [],
    sideEffects: [],
  },
  {
    id: "30",
    name: "Blood Pressure Monitor (Dr. Morepen)",
    price: 2200.00,
    category: "Medical Devices & Mobility Aids",
    description: "Blood Pressure Monitor",
    uses: [],
    sideEffects: [],
  },
];
